### ISSUE TITLE
Error locating  PyQuadSim

### ISSUE THREAD

**Issue by lightng03** [simondlevy/PyQuadSim#4]
Hello,

I am trying to run this but i keep getting the following error. 
![screenshot from 2016-02-21 01 52 45](https://cloud.githubusercontent.com/assets/6937345/13202017/f7830db0-d83e-11e5-9151-68e23fa946e2.png)
and I looked at the child scripts available but i dont see any PyQuadSim.
![screenshot from 2016-02-21 01 53 01](https://cloud.githubusercontent.com/assets/6937345/13202020/11289636-d83f-11e5-81d1-9e60b4a46e64.png)
I would appreciate some help. 
I am running Vrep 3.23 rev4 64 bit. 
when I run the qstest.py script from pyquadstick I can see that my controller is being detected.
I moved my PyQuadsim folder to the Vrep base folder (I think I am doing something wrong here as the script is not getting detected)

Cheers.

**Comment by simondlevy** [comment]
Sorry about that!  I believe I've fixed this bug.  Please grab the latest repo and try again.
